config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'

  resources :lists
  resources :tasks

  put "/task/:id/update", to: "tasks#js_update"
  delete "/delete_attachment", to: "tasks#delete_attachment", as: "delete_attachment"
end

app/models/list.rb
require "csv"

class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  validates :title, presence: true, length: { minimum: 1 }

  def self.export_as_a_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |list|
        csv <<list.attributes.values_at(*column_names)
      end
    end
  end

  def export_as_a_csv
    CSV.generate do |csv|
      csv << column_names
      csv << self.attributes.values_at(*column_names)
    end
  end
end

app/models/task.rb
require "csv"

class Task < ActiveRecord::Base

  attr_accessor :attachment

  has_attached_file :attachment, default_url: "alpaca.jpg",
                                 storage: :s3,
                                 s3_credentials: {
                                   access_key_id: ENV['AWSAccessKeyId'],
                                   bucket: ENV['S3_BUCKET_NAME'],
                                   secret_access_key: ENV['AWSSecretKey'] }

  validates_attachment_content_type :attachment, content_type: /\Aimage\/.*\Z/


  belongs_to :list

  validates :title, presence: true, length: { minimum: 1 }
  validate :start_date_cannot_be_in_the_past
  validate :due_date_cannot_be_in_the_past_or_before_start

  after_create :set_start_date_and_due_date_if_none_specified

  def completion_status
    if status
      "Complete"
    else
      "Incomplete"
    end
  end

  def default_filter?
    status || start_date < Date.today
  end

  def status_update
    new_status = !status
    self.update(status: new_status)
  end

  def not_in_the_future?
    if start_date > Date.today
      false
    else
      true
    end
  end

  def send_email_to_user_if_desired(task_title)
    if wants_to_be_notified?(task_title)
      email = retrieve_email_address(task_title)
      UserNotifier.send_new_task_email(email, self).deliver
    end
  end

  def send_status_change_email
    if wants_to_be_notified?(self.title)
      email = retrieve_email_address(self.title)
      UserNotifier.task_status_changed(email, self).deliver
    end
  end

  def remove_attachment
    self.update(attachment: nil)
    self.save
  end

  def self.export_as_a_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |task|
        csv << task.attributes.values_at(*column_names)
      end
    end
  end

  private

  def retrieve_email_address(title)
    index_of_email = title_words(title).index("/cc") + 1
    title_words(title)[index_of_email]
  end

  def title_words(title)
    title.split(" ")
  end

  def wants_to_be_notified?(title)
    title_words(title).include?("/cc")
  end

  def set_start_date_and_due_date_if_none_specified
    self.update(start_date: Date.today ) if start_date.nil?
    self.update(due_date: Date.today + 1 ) if due_date.nil?
  end

  def start_date_cannot_be_in_the_past
    errors.add(:start_date, "can't be before today") if
    !start_date.blank? && start_date < Date.today
  end

  def due_date_cannot_be_in_the_past_or_before_start
    errors.add(:due_date, "can't be before today") if
    !due_date.blank? && due_date < Date.today
  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :list
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all

    respond_to do |format|
      format.html
      format.csv { send_data @lists.export_as_a_csv }
    end
  end

  def show
    @list = List.find_by!(id: params[:id])
    @tasks = @list.tasks
  end

  def new
    @list = List.new
  end

  def edit
    @list = List.find_by!(id: params[:id])
  end

  def create
    list = List.new(list_params)
    if list.save
      flash[:success] = "List Added"
      redirect_to list
    else
      flash[:danger] = list.errors.full_messages.join(", ")
      redirect_to request.referrer
    end
  end

  def update
    list = List.find_by!(id: params[:id])
    list.update(list_params)
    if list.save
      flash[:success] = "List Updated"
      redirect_to list
    else
      flash[:danger] = list.errors.full_messages.join(", ")
      redirect_to request.referrer
    end
  end

  def destroy
    list = List.find_by!(id: params[:id])
    if list.destroy
      flash[:danger] = "List Deleted"
      redirect_to lists_path
    else
      flash[:danger] = "An error occured while trying to delete your list. Please try again"
      redirect_to request.referrer
    end
  end

  private

  def list_params
    params.require(:list).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html
      format.csv { send_data @tasks.export_as_a_csv }
    end
  end

  def show
    @task = Task.find_by!(id: params[:id])
  end

  def new
    @task = Task.new(list_id: params[:list_id])
  end

  def edit
    @task = Task.find_by!(id: params[:id])
  end

  def create
    task = Task.create(task_params)
    if task.save
      task.send_email_to_user_if_desired(params[:task][:title])
      flash[:success] = "Task Created"
      redirect_to list_path(task.list_id)
    else
      flash[:danger] = task.errors.full_messages.join(", ")
      redirect_to list_path(task.list_id)
    end
  end

  def update
    task = Task.find_by!(id: params[:id])
    if task.update(task_params)
      flash[:success] = "Task Updated"
      redirect_to list_path(task.list.id)
    else
      flash[:danger] = task.errors.full_messages.join(", ")
      redirect_to edit_task_path
    end
  end

  def js_update
    task = Task.find_by!(id: params[:id])
    task.send_status_change_email
    task.status_update

    render nothing: true, status: 200, content_type: 'text/html'
  end

  def delete_attachment
    task = Task.find_by!(id: params[:id])
    task.remove_attachment

    redirect_to request.referrer
  end

  private

    def task_params
      params.require(:task).permit(:title,
                                   :status,
                                   :notes,
                                   :due_date,
                                   :start_date,
                                   :list_id,
                                   :attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>List-Y-List</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/nav" %>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class => "flash_#{name}" %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
<%= f.label "List Title" %>
<%= f.text_field :title, placeholder: "Your new Lists Title" %>
<%= f.label "List Description" %>
<%= f.text_field :description, placeholder: "You new Lists Description" %>
<%= f.submit "Submit List", class: "btn btn-large" %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <h2 class="center-align">Edit @list.title List</h2>
  <%= render "form" %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s8 offset-s2">

    <h1 class="center-align">List-y-List</h1>
    <h5 class="center-align"><%= button_to "Create New List", new_list_path, method: "get", class: "btn btn-large center" %></h5>
      <ol class="list_list hoverable collection">
        <% @lists.each do |list| %>
          <li class="collection-item"><%= link_to list.title, list_path(list) %> - <%= list.description %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h2 class="center-align">Make a new List</h2>
  <%= render 'form' %>
</div>

app/views/lists/show.html.erb
<div class="list_buttons">
  <h4>List Options</h4>
  <%= button_to "Edit", edit_list_path(@list), method: 'get', class: "btn " %>
  <%= button_to "Delete", list_path(@list), method: 'delete', class: "btn  red" %>
  <%= link_to "Create New Task", new_task_path(list_id: @list), class: "btn yellow" %>
</div>
<div class="container">
  <h1 class="center-align"><%= @list.title %></h1>
  <div class="filter_buttons">
    <h3 class="center-align">Filter Buttons</h3>
    <button type="button" class="btn grey toggle_all_tasks" name="button">All Tasks</button>
    <button type="button" class="btn grey toggle_completed_tasks" name="button">Completed Tasks</button>
    <button type="button" class="btn grey toggle_incompleted_tasks" name="button">Incompleted Tasks</button>
    <button type="button" class="btn grey toggle_future_tasks" name="button">Future Tasks</button><br>
    <div class="row">
    <div class=" col s6">
      <input  id="start_date_filter" type="text">
      <label class="active" for="start_date_filter">Filter Start Date</label>
    </div>
    <div class=" col s6">
      <input  id="due_date_filter" type="text">
      <label class="active" for="due_date_filter">Filter Due Date</label>
    </div>
    <div class=" col s6 offset-s3">
      <input id="search_bar" type="text">
      <label for="search_bar" class="s-12" id="searchlabel">Search Tasks</label>
    </div>
  </div>
  </div>
  <div class="sort_buttons">
    <h3 class="center-align">Sort Buttons</h3>
    <button type="button" class="btn grey lighten-2 sort_title" name="button">Title</button>
    <button type="button" class="btn grey lighten-2 sort_status" name="button">Status</button>
    <button type="button" class="btn grey lighten-2 sort_due_date" name="button">Due Date</button>
    <button type="button" class="btn grey lighten-2 sort_start_date" name="button">Start Date</button>
  </div>
  <h3>List Description: <%= @list.description %></h3>
  <table class="hoverable">
    <thead>
      <tr>
        <td>Title</td>
        <td>Notes</td>
        <td>Start Date</td>
        <td>Due Date</td>
        <td>Status</td>
        <td>Change Status</td>
        <td></td>
      </tr>
    </thead>
    <tbody class="task_list">
      <% @tasks.each do |task| %>
        <% if task.default_filter? %>
          <tr class="hidden" data-id="<%= task.id %>" data-status="<%= task.status %>" data-not-future-task="<%= task.not_in_the_future? %>">
            <td><%= link_to task.title, edit_task_path(task, list_id: @list) %></td>
            <td><%= task.notes %></td>
            <td><%= task.start_date %></td>
            <td><%= task.due_date %></td>
            <td><%= task.completion_status %></td>
            <td><button type="button" class="btn yellow darken-2 task_complete" name="button">Mark Incomplete</button></td>
            <td><%= image_tag task.attachment.url(:micro) %><%= link_to "Delete Attachment", delete_attachment_path( id: task.id), method: "delete" %></td>
          </tr>
        <% else %>
          <tr data-id="<%= task.id %>" data-status="<%= task.status %>" data-not-future-task="<%= task.not_in_the_future? %>">
            <td><%= link_to task.title, edit_task_path(task, list_id: @list) %></td>
            <td><%= task.notes %></td>
            <td><%= task.start_date %></td>
            <td><%= task.due_date %></td>
            <td><%= task.completion_status %></td>
            <td><button type="button" class="btn green task_complete" name="button">Mark Complete</button></td>
            <td><%= image_tag task.attachment.url(:micro) %><%= link_to "Delete Attachment", delete_attachment_path( id: task.id), method: "delete" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_nav.html.erb
<div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper black">
        <a href="/lists" class="brand-logo center">List-y-List</a>
        <ul>
          <li class="col s6 container">

          </li>
        </ul>
      </div>
        <ul id=" dropdown1" class="dropdown-content">
          <li><%= link_to "Lists", lists_path %>HELLO</li>
          <li class="divider"></li>
          <li><%= link_to "All Tasks Ever", tasks_path %></li>
        </ul>
    </nav>
  </div>

app/views/tasks/_form.html.erb
<%= form_for @task, html: { :multipart => true } do |f| %>
  <%= f.hidden_field :list_id, value: params[:list_id] %>
  <%= f.label "Title" %>
  <%= f.text_field :title, class: "form-control", placeholder: "... Pro Tip: end the title with '/cc your_email@example.com' and you'll get email updates" %>
  <%= f.label "Notes" %>
  <%= f.text_field :notes, class: "form-control" %>
  <%= f.label "Start Date" %>
  <%= f.date_field :start_date, class: "form-control" %>
  <%= f.label "Due Date" %>
  <%= f.date_field :due_date, class: "form-control" %>
  <%= f.label "Upload Attachment" %>
  <%= f.file_field :attachment %>
  <%= f.submit class: "btn" %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="center-align">Edit <%= @task.title %></h1>
  <%= render "form" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="center-align">Add A New Task</h1>
  <%= render "form" %>
</div>

app/views/user_notifier/send_new_task_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>You Just Added @task.title to your <%= @task.list.title %> list </h1>
    <ul>
      <li>Task Completed?: <%= @task.status %></li>
      <li>Task Notes: <%= @task.notes %></li>
      <li>Task Due Date: <%= @task.due_date %></li>
    </ul>

  </body>
</html>

app/views/user_notifier/task_status_changed.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>The Status of @task.title just changed on your <%= @task.list.title %> list </h1>
    <ul>
      <li>Task Status: <%= @task.status %></li>
      <li>Task Notes: <%= @task.notes %></li>
      <li>Task Due Date: <%= @task.due_date %></li>
    </ul>

  </body>
</html>